[build]
  publish = "public"
  command = "yarn run build"

[context.deploy-preview.environment]
  GIT_LFS_ENABLED ="true"
  NODE_VERSION = "14.*"

[context.production.environment]
  GIT_LFS_ENABLED ="true"
  NODE_VERSION = "16"
