name: Cleanup Codespaces
on:
  workflow_dispatch:
  pull_request:
    types:
      - "closed"

jobs:
  cleanup:
    name: Cleanup
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: FranzDiebold/github-env-vars-action@v1.2.1
    - name: Print environment variables
      run: |
        echo "GITHUB_REPOSITORY_SLUG=$GITHUB_REPOSITORY_SLUG"
        echo "GITHUB_REPOSITORY_OWNER=$GITHUB_REPOSITORY_OWNER"
        echo "GITHUB_REPOSITORY_OWNER_SLUG=$GITHUB_REPOSITORY_OWNER_SLUG"
        echo "GITHUB_REPOSITORY_NAME=$GITHUB_REPOSITORY_NAME"
        echo "GITHUB_REPOSITORY_NAME_SLUG=$GITHUB_REPOSITORY_NAME_SLUG"
        echo "GITHUB_REF_SLUG=$GITHUB_REF_SLUG"
        echo "GITHUB_REF_NAME=$GITHUB_REF_NAME"
        echo "GITHUB_REF_NAME_SLUG=$GITHUB_REF_NAME_SLUG"
        echo "GITHUB_SHA_SHORT=$GITHUB_SHA_SHORT"
    - name: Cleanup Codespace for PullRequest
      run: |
        echo "${GITHUB_REF_NAME}"
        source .github/workflows/github_api_codespaces.sh
        target_codespaces=$(get_pullreq_unused_spaces "${{ secrets.CODESPACE_TOKEN }}" "legnoh" "leglog" "${GITHUB_REF_NAME}")
        echo ${target_codespaces}
        echo ${target_codespaces} | while read line; do
          delete_codespace "${{ secrets.CODESPACE_TOKEN }}" "legnoh" "${line}"
        done
