name: Cleanup Codespaces
on:
  workflow_dispatch:
  pull_request:
    types:
      - "closed"
    paths: [ content/posts/**.md ]

jobs:
  nightly:
    name: Deploy nightly
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Empty Codespace
        uses: NickLiffen/delete-empty-codespaces@v1.0.0
        with:
          GITHUB_TOKEN: ${{ secrets.CODESPACE_TOKEN }}
